stages:
  - Build
  - Setting
  - Deploy

Docker Image Build:
  stage: Build
  image: docker:latest
  before_script:
    - cd /volume1/docker/Commute-Front
    - git pull origin master
  script:
    - docker build --tag commute/front .
  only:
    - tags

Docker Remove Container:
  stage: Setting
  image: docker:latest
  script:
    - docker stop Commute-Front
    - docker rm Commute-Front
  only:
    - tags

# Docker Image Delete:
#   stage: Setting
#   image: docker:latest
#   script:
#     - docker rmi `docker images |  awk '$1 ~ /commute\/front/ {print $3}'`
#   only:
#     - tags

Docker Run Container:
  stage: Deploy
  image: docker:latest
  script:
    - docker run -d --name=Commute-Front --restart=always -p 19932:3000 commute/front:latest
  only:
    - tags
